version: '2'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    #command: sh -c "npm run autobuild"
    command: sh -c "npm run dev"

    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - app_svelte_node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
volumes:
  app_svelte_node_modules:
